require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/telescope")
-- require("plugins/dashboard")
require("plugins/toggleterm")
