require("plugins.plugins-setup")

require("core.neovide")
require("core.options")
require("core.keymaps")

require("plugins/nvim-tree")
require("plugins/treesitter")
-- require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/telescope")
-- require("plugins/dashboard")
require("plugins/toggleterm")
require("plugins/coc")
require("plugins/transparent")
require("plugins/lualine")
-- require("plugins/lspsaga")
-- require("plugins/null_ls")
require("plugins/prettier")
require("plugins/leap")
